apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-server
  name: http-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      restartPolicy: Always
      containers:
      - image: http-server
        imagePullPolicy: Never
        name: http-server
        livenessProbe:
           exec:
             command: 
             - curl
             - --http0.9
             - 0.0.0.0/healthcheck
           initialDelaySeconds: 2
           periodSeconds: 3
        readinessProbe:
           exec:
             command: 
             - curl
             - --http0.9
             - 0.0.0.0/healthcheck
           initialDelaySeconds: 2
           periodSeconds: 4
        ports:
        - containerPort: 80
#          hostPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1024m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 128Mi